services:
  frontend:
    image: sinitsabogdan/film-nest-app-frontend:node20-alpine
    container_name: frontend
    networks:
      - frontend_net
    volumes:
      - frontend_dist:/app/dist

  backend:
    image: sinitsabogdan/film-nest-app-backend:node20-alpine
    container_name: backend
    networks:
      - backend_net
    restart: unless-stopped
    environment:
      - DATABASE_DRIVER=postgres
      - DATABASE_URL=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=root
      - DATABASE_URL=postgresql://postgres:admin@root:5434/films
      - LOGGER=tskv
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./initDB/:/docker-entrypoint-initdb.d
      - postgres_data:/usr/local/pgsql/data
    networks:
      - backend_net
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - 8080:80
    networks:
      - backend_net
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=sinitsa.bogdan.1997@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=postgres

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend_net
      - backend_net
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
      - frontend_dist:/var/www/frontend:ro

  certbot:
    image: certbot/certbot:latest
    networks:
      - frontend_net
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  postgres_data:
  frontend_dist:

networks:
  frontend_net:
  backend_net: